-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity findLayersPopulation is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    LRHLS_layersPopulation_4_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    LRHLS_layersPopulation_5_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    LRHLS_layersPopulation_6_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    stubs_0_layer_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    stubs_1_layer_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    stubs_2_layer_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    stubs_3_layer_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    stubs_0_valid_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    stubs_1_valid_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    stubs_2_valid_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    stubs_3_valid_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of findLayersPopulation is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

    signal stubs_3_valid_V_read11_reg_1142 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal stubs_3_valid_V_read11_reg_1142_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_2_valid_V_read_2_reg_1146 : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_1_valid_V_read_2_reg_1150 : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_3_layer_V_read_2_reg_1157 : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_3_layer_V_read_2_reg_1157_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_2_layer_V_read_2_reg_1169 : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_1_layer_V_read_2_reg_1181 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_6_V_fu_423_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_0_valid_V_read_2_read_fu_54_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal LRHLS_layersPopulation_5_V_fu_445_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_4_V_fu_467_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_3_V_fu_489_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_2_V_fu_511_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_1_V_fu_533_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_0_V_fu_555_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_6_V_2_fu_602_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_5_V_2_fu_623_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_4_V_2_fu_644_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_3_V_2_fu_665_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_2_V_2_fu_686_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_1_V_2_fu_707_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_0_V_2_fu_728_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_6_V_4_fu_774_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_5_V_4_fu_795_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_4_V_4_fu_816_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_3_V_4_fu_837_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_2_V_4_fu_858_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_1_V_4_fu_879_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_0_V_4_fu_900_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_1_reg_102 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_1_reg_114 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_1_reg_126 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_1_reg_138 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_1_reg_150 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_1_reg_160 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_1_reg_170 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_3_reg_180 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_3_reg_180 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_3_reg_191 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_3_reg_191 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_3_reg_202 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_3_reg_202 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_3_reg_213 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_3_reg_213 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_3_reg_224 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_3_reg_224 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_3_reg_235 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_3_reg_235 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_3_reg_246 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_3_reg_246 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_5_reg_257 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_5_reg_257 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_5_reg_257 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_5_reg_267 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_5_reg_267 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_5_reg_267 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_5_reg_277 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_5_reg_277 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_5_reg_277 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_5_reg_287 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_5_reg_287 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_5_reg_287 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_5_reg_297 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_5_reg_297 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_5_reg_297 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_5_reg_307 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_5_reg_307 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_5_reg_307 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_5_reg_317 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_5_reg_317 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_5_reg_317 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_0_V_6_fu_1078_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_7_reg_327 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_1_V_6_fu_1056_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_7_reg_337 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_2_V_6_fu_1034_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_7_reg_347 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_3_V_6_fu_1012_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_7_reg_357 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_4_V_6_fu_990_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_7_reg_367 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_5_V_6_fu_968_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_7_reg_377 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_6_V_6_fu_946_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_7_reg_387 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_397_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln700_fu_417_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_577_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln700_1_fu_596_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_749_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln700_2_fu_768_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_921_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln700_3_fu_940_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal LRHLS_layersPopulation_4_V_read_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_5_V_read_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal LRHLS_layersPopulation_6_V_read_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_0_layer_V_read_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_1_layer_V_read_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_2_layer_V_read_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_3_layer_V_read_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal stubs_0_valid_V_read_int_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_1_valid_V_read_int_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_2_valid_V_read_int_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal stubs_3_valid_V_read_int_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_5_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_6_int_reg : STD_LOGIC_VECTOR (2 downto 0);

    component LRHLS_top_mux_73_3_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (2 downto 0);
        din3 : IN STD_LOGIC_VECTOR (2 downto 0);
        din4 : IN STD_LOGIC_VECTOR (2 downto 0);
        din5 : IN STD_LOGIC_VECTOR (2 downto 0);
        din6 : IN STD_LOGIC_VECTOR (2 downto 0);
        din7 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component LRHLS_top_mux_83_3_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (2 downto 0);
        din3 : IN STD_LOGIC_VECTOR (2 downto 0);
        din4 : IN STD_LOGIC_VECTOR (2 downto 0);
        din5 : IN STD_LOGIC_VECTOR (2 downto 0);
        din6 : IN STD_LOGIC_VECTOR (2 downto 0);
        din7 : IN STD_LOGIC_VECTOR (2 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;



begin
    LRHLS_top_mux_73_3_1_0_U21 : component LRHLS_top_mux_73_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_const_lv3_0,
        din1 => ap_const_lv3_0,
        din2 => ap_const_lv3_0,
        din3 => ap_const_lv3_0,
        din4 => LRHLS_layersPopulation_4_V_read_int_reg,
        din5 => LRHLS_layersPopulation_5_V_read_int_reg,
        din6 => LRHLS_layersPopulation_6_V_read_int_reg,
        din7 => stubs_0_layer_V_read_int_reg,
        dout => tmp_fu_397_p9);

    LRHLS_top_mux_83_3_1_0_U22 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => LRHLS_layersPopulation_6_V_read_int_reg,
        din1 => LRHLS_layersPopulation_6_V_read_int_reg,
        din2 => LRHLS_layersPopulation_6_V_read_int_reg,
        din3 => LRHLS_layersPopulation_6_V_read_int_reg,
        din4 => LRHLS_layersPopulation_6_V_read_int_reg,
        din5 => LRHLS_layersPopulation_6_V_read_int_reg,
        din6 => add_ln700_fu_417_p2,
        din7 => add_ln700_fu_417_p2,
        din8 => stubs_0_layer_V_read_int_reg,
        dout => LRHLS_layersPopulation_6_V_fu_423_p10);

    LRHLS_top_mux_83_3_1_0_U23 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => LRHLS_layersPopulation_5_V_read_int_reg,
        din1 => LRHLS_layersPopulation_5_V_read_int_reg,
        din2 => LRHLS_layersPopulation_5_V_read_int_reg,
        din3 => LRHLS_layersPopulation_5_V_read_int_reg,
        din4 => LRHLS_layersPopulation_5_V_read_int_reg,
        din5 => add_ln700_fu_417_p2,
        din6 => LRHLS_layersPopulation_5_V_read_int_reg,
        din7 => LRHLS_layersPopulation_5_V_read_int_reg,
        din8 => stubs_0_layer_V_read_int_reg,
        dout => LRHLS_layersPopulation_5_V_fu_445_p10);

    LRHLS_top_mux_83_3_1_0_U24 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => LRHLS_layersPopulation_4_V_read_int_reg,
        din1 => LRHLS_layersPopulation_4_V_read_int_reg,
        din2 => LRHLS_layersPopulation_4_V_read_int_reg,
        din3 => LRHLS_layersPopulation_4_V_read_int_reg,
        din4 => add_ln700_fu_417_p2,
        din5 => LRHLS_layersPopulation_4_V_read_int_reg,
        din6 => LRHLS_layersPopulation_4_V_read_int_reg,
        din7 => LRHLS_layersPopulation_4_V_read_int_reg,
        din8 => stubs_0_layer_V_read_int_reg,
        dout => LRHLS_layersPopulation_4_V_fu_467_p10);

    LRHLS_top_mux_83_3_1_0_U25 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_const_lv3_0,
        din1 => ap_const_lv3_0,
        din2 => ap_const_lv3_0,
        din3 => add_ln700_fu_417_p2,
        din4 => ap_const_lv3_0,
        din5 => ap_const_lv3_0,
        din6 => ap_const_lv3_0,
        din7 => ap_const_lv3_0,
        din8 => stubs_0_layer_V_read_int_reg,
        dout => LRHLS_layersPopulation_3_V_fu_489_p10);

    LRHLS_top_mux_83_3_1_0_U26 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_const_lv3_0,
        din1 => ap_const_lv3_0,
        din2 => add_ln700_fu_417_p2,
        din3 => ap_const_lv3_0,
        din4 => ap_const_lv3_0,
        din5 => ap_const_lv3_0,
        din6 => ap_const_lv3_0,
        din7 => ap_const_lv3_0,
        din8 => stubs_0_layer_V_read_int_reg,
        dout => LRHLS_layersPopulation_2_V_fu_511_p10);

    LRHLS_top_mux_83_3_1_0_U27 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_const_lv3_0,
        din1 => add_ln700_fu_417_p2,
        din2 => ap_const_lv3_0,
        din3 => ap_const_lv3_0,
        din4 => ap_const_lv3_0,
        din5 => ap_const_lv3_0,
        din6 => ap_const_lv3_0,
        din7 => ap_const_lv3_0,
        din8 => stubs_0_layer_V_read_int_reg,
        dout => LRHLS_layersPopulation_1_V_fu_533_p10);

    LRHLS_top_mux_83_3_1_0_U28 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => add_ln700_fu_417_p2,
        din1 => ap_const_lv3_0,
        din2 => ap_const_lv3_0,
        din3 => ap_const_lv3_0,
        din4 => ap_const_lv3_0,
        din5 => ap_const_lv3_0,
        din6 => ap_const_lv3_0,
        din7 => ap_const_lv3_0,
        din8 => stubs_0_layer_V_read_int_reg,
        dout => LRHLS_layersPopulation_0_V_fu_555_p10);

    LRHLS_top_mux_73_3_1_0_U29 : component LRHLS_top_mux_73_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din1 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din2 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din3 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din4 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din5 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din6 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170,
        din7 => stubs_1_layer_V_read_2_reg_1181,
        dout => tmp_1_fu_577_p9);

    LRHLS_top_mux_83_3_1_0_U30 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170,
        din1 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170,
        din2 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170,
        din3 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170,
        din4 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170,
        din5 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170,
        din6 => add_ln700_1_fu_596_p2,
        din7 => add_ln700_1_fu_596_p2,
        din8 => stubs_1_layer_V_read_2_reg_1181,
        dout => LRHLS_layersPopulation_6_V_2_fu_602_p10);

    LRHLS_top_mux_83_3_1_0_U31 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din1 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din2 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din3 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din4 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din5 => add_ln700_1_fu_596_p2,
        din6 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din7 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160,
        din8 => stubs_1_layer_V_read_2_reg_1181,
        dout => LRHLS_layersPopulation_5_V_2_fu_623_p10);

    LRHLS_top_mux_83_3_1_0_U32 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din1 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din2 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din3 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din4 => add_ln700_1_fu_596_p2,
        din5 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din6 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din7 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150,
        din8 => stubs_1_layer_V_read_2_reg_1181,
        dout => LRHLS_layersPopulation_4_V_2_fu_644_p10);

    LRHLS_top_mux_83_3_1_0_U33 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din1 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din2 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din3 => add_ln700_1_fu_596_p2,
        din4 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din5 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din6 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din7 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138,
        din8 => stubs_1_layer_V_read_2_reg_1181,
        dout => LRHLS_layersPopulation_3_V_2_fu_665_p10);

    LRHLS_top_mux_83_3_1_0_U34 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din1 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din2 => add_ln700_1_fu_596_p2,
        din3 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din4 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din5 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din6 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din7 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126,
        din8 => stubs_1_layer_V_read_2_reg_1181,
        dout => LRHLS_layersPopulation_2_V_2_fu_686_p10);

    LRHLS_top_mux_83_3_1_0_U35 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din1 => add_ln700_1_fu_596_p2,
        din2 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din3 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din4 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din5 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din6 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din7 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114,
        din8 => stubs_1_layer_V_read_2_reg_1181,
        dout => LRHLS_layersPopulation_1_V_2_fu_707_p10);

    LRHLS_top_mux_83_3_1_0_U36 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => add_ln700_1_fu_596_p2,
        din1 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din2 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din3 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din4 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din5 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din6 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din7 => ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102,
        din8 => stubs_1_layer_V_read_2_reg_1181,
        dout => LRHLS_layersPopulation_0_V_2_fu_728_p10);

    LRHLS_top_mux_73_3_1_0_U37 : component LRHLS_top_mux_73_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din1 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din2 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din3 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din4 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din5 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din6 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246,
        din7 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => tmp_2_fu_749_p9);

    LRHLS_top_mux_83_3_1_0_U38 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246,
        din1 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246,
        din2 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246,
        din3 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246,
        din4 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246,
        din5 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246,
        din6 => add_ln700_2_fu_768_p2,
        din7 => add_ln700_2_fu_768_p2,
        din8 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => LRHLS_layersPopulation_6_V_4_fu_774_p10);

    LRHLS_top_mux_83_3_1_0_U39 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din1 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din2 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din3 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din4 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din5 => add_ln700_2_fu_768_p2,
        din6 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din7 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235,
        din8 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => LRHLS_layersPopulation_5_V_4_fu_795_p10);

    LRHLS_top_mux_83_3_1_0_U40 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din1 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din2 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din3 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din4 => add_ln700_2_fu_768_p2,
        din5 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din6 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din7 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224,
        din8 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => LRHLS_layersPopulation_4_V_4_fu_816_p10);

    LRHLS_top_mux_83_3_1_0_U41 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din1 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din2 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din3 => add_ln700_2_fu_768_p2,
        din4 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din5 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din6 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din7 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213,
        din8 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => LRHLS_layersPopulation_3_V_4_fu_837_p10);

    LRHLS_top_mux_83_3_1_0_U42 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din1 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din2 => add_ln700_2_fu_768_p2,
        din3 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din4 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din5 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din6 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din7 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202,
        din8 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => LRHLS_layersPopulation_2_V_4_fu_858_p10);

    LRHLS_top_mux_83_3_1_0_U43 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din1 => add_ln700_2_fu_768_p2,
        din2 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din3 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din4 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din5 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din6 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din7 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191,
        din8 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => LRHLS_layersPopulation_1_V_4_fu_879_p10);

    LRHLS_top_mux_83_3_1_0_U44 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => add_ln700_2_fu_768_p2,
        din1 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din2 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din3 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din4 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din5 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din6 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din7 => ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180,
        din8 => stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg,
        dout => LRHLS_layersPopulation_0_V_4_fu_900_p10);

    LRHLS_top_mux_73_3_1_0_U45 : component LRHLS_top_mux_73_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din1 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din2 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din3 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din4 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din5 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din6 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317,
        din7 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => tmp_3_fu_921_p9);

    LRHLS_top_mux_83_3_1_0_U46 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317,
        din1 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317,
        din2 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317,
        din3 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317,
        din4 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317,
        din5 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317,
        din6 => add_ln700_3_fu_940_p2,
        din7 => add_ln700_3_fu_940_p2,
        din8 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => LRHLS_layersPopulation_6_V_6_fu_946_p10);

    LRHLS_top_mux_83_3_1_0_U47 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din1 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din2 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din3 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din4 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din5 => add_ln700_3_fu_940_p2,
        din6 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din7 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307,
        din8 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => LRHLS_layersPopulation_5_V_6_fu_968_p10);

    LRHLS_top_mux_83_3_1_0_U48 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din1 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din2 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din3 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din4 => add_ln700_3_fu_940_p2,
        din5 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din6 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din7 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297,
        din8 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => LRHLS_layersPopulation_4_V_6_fu_990_p10);

    LRHLS_top_mux_83_3_1_0_U49 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din1 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din2 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din3 => add_ln700_3_fu_940_p2,
        din4 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din5 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din6 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din7 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287,
        din8 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => LRHLS_layersPopulation_3_V_6_fu_1012_p10);

    LRHLS_top_mux_83_3_1_0_U50 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din1 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din2 => add_ln700_3_fu_940_p2,
        din3 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din4 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din5 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din6 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din7 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277,
        din8 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => LRHLS_layersPopulation_2_V_6_fu_1034_p10);

    LRHLS_top_mux_83_3_1_0_U51 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din1 => add_ln700_3_fu_940_p2,
        din2 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din3 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din4 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din5 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din6 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din7 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267,
        din8 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => LRHLS_layersPopulation_1_V_6_fu_1056_p10);

    LRHLS_top_mux_83_3_1_0_U52 : component LRHLS_top_mux_83_3_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => add_ln700_3_fu_940_p2,
        din1 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din2 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din3 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din4 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din5 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din6 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din7 => ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257,
        din8 => stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg,
        dout => LRHLS_layersPopulation_0_V_6_fu_1078_p10);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;

    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102 <= ap_const_lv3_0;
                elsif ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102 <= LRHLS_layersPopulation_0_V_fu_555_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_1_reg_102;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114 <= ap_const_lv3_0;
                elsif ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114 <= LRHLS_layersPopulation_1_V_fu_533_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_1_reg_114;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126 <= ap_const_lv3_0;
                elsif ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126 <= LRHLS_layersPopulation_2_V_fu_511_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_1_reg_126;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138 <= ap_const_lv3_0;
                elsif ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138 <= LRHLS_layersPopulation_3_V_fu_489_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_1_reg_138;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150 <= LRHLS_layersPopulation_4_V_read_int_reg;
                elsif ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150 <= LRHLS_layersPopulation_4_V_fu_467_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_1_reg_150;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160 <= LRHLS_layersPopulation_5_V_read_int_reg;
                elsif ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160 <= LRHLS_layersPopulation_5_V_fu_445_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_1_reg_160;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170 <= LRHLS_layersPopulation_6_V_read_int_reg;
                elsif ((stubs_0_valid_V_read_2_read_fu_54_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170 <= LRHLS_layersPopulation_6_V_fu_423_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_1_reg_170;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102;
                elsif ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180 <= LRHLS_layersPopulation_0_V_2_fu_728_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_3_reg_180;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114;
                elsif ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191 <= LRHLS_layersPopulation_1_V_2_fu_707_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_3_reg_191;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126;
                elsif ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202 <= LRHLS_layersPopulation_2_V_2_fu_686_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_3_reg_202;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138;
                elsif ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213 <= LRHLS_layersPopulation_3_V_2_fu_665_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_3_reg_213;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150;
                elsif ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224 <= LRHLS_layersPopulation_4_V_2_fu_644_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_3_reg_224;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160;
                elsif ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235 <= LRHLS_layersPopulation_5_V_2_fu_623_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_3_reg_235;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170;
                elsif ((stubs_1_valid_V_read_2_reg_1150 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246 <= LRHLS_layersPopulation_6_V_2_fu_602_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_3_reg_246;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180;
                elsif ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257 <= LRHLS_layersPopulation_0_V_4_fu_900_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_5_reg_257;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191;
                elsif ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267 <= LRHLS_layersPopulation_1_V_4_fu_879_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_5_reg_267;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202;
                elsif ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277 <= LRHLS_layersPopulation_2_V_4_fu_858_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_5_reg_277;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213;
                elsif ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287 <= LRHLS_layersPopulation_3_V_4_fu_837_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_5_reg_287;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224;
                elsif ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297 <= LRHLS_layersPopulation_4_V_4_fu_816_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_5_reg_297;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235;
                elsif ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307 <= LRHLS_layersPopulation_5_V_4_fu_795_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_5_reg_307;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246;
                elsif ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317 <= LRHLS_layersPopulation_6_V_4_fu_774_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_5_reg_317;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                LRHLS_layersPopulation_4_V_read_int_reg <= LRHLS_layersPopulation_4_V_read;
                LRHLS_layersPopulation_5_V_read_int_reg <= LRHLS_layersPopulation_5_V_read;
                LRHLS_layersPopulation_6_V_read_int_reg <= LRHLS_layersPopulation_6_V_read;
                stubs_0_layer_V_read_int_reg <= stubs_0_layer_V_read;
                stubs_0_valid_V_read_int_reg <= stubs_0_valid_V_read;
                stubs_1_layer_V_read_int_reg <= stubs_1_layer_V_read;
                stubs_1_valid_V_read_int_reg <= stubs_1_valid_V_read;
                stubs_2_layer_V_read_int_reg <= stubs_2_layer_V_read;
                stubs_2_valid_V_read_int_reg <= stubs_2_valid_V_read;
                stubs_3_layer_V_read_int_reg <= stubs_3_layer_V_read;
                stubs_3_valid_V_read_int_reg <= stubs_3_valid_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_3_reg_180 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_3_reg_180;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_5_reg_257;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_3_reg_191 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_3_reg_191;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_5_reg_267;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_3_reg_202 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_3_reg_202;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_5_reg_277;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_3_reg_213 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_3_reg_213;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_5_reg_287;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_3_reg_224 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_3_reg_224;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_5_reg_297;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_3_reg_235 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_3_reg_235;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_5_reg_307;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_3_reg_246 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_3_reg_246;
                ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_5_reg_317;
                ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_5_reg_257;
                ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_5_reg_267;
                ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_5_reg_277;
                ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_5_reg_287;
                ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_5_reg_297;
                ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_5_reg_307;
                ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_5_reg_317;
                stubs_1_layer_V_read_2_reg_1181 <= stubs_1_layer_V_read_int_reg;
                stubs_1_valid_V_read_2_reg_1150 <= stubs_1_valid_V_read_int_reg;
                stubs_2_layer_V_read_2_reg_1169 <= stubs_2_layer_V_read_int_reg;
                stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg <= stubs_2_layer_V_read_2_reg_1169;
                stubs_2_valid_V_read_2_reg_1146 <= stubs_2_valid_V_read_int_reg;
                stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg <= stubs_2_valid_V_read_2_reg_1146;
                stubs_3_layer_V_read_2_reg_1157 <= stubs_3_layer_V_read_int_reg;
                stubs_3_layer_V_read_2_reg_1157_pp0_iter1_reg <= stubs_3_layer_V_read_2_reg_1157;
                stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg <= stubs_3_layer_V_read_2_reg_1157_pp0_iter1_reg;
                stubs_3_valid_V_read11_reg_1142 <= stubs_3_valid_V_read_int_reg;
                stubs_3_valid_V_read11_reg_1142_pp0_iter1_reg <= stubs_3_valid_V_read11_reg_1142;
                stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg <= stubs_3_valid_V_read11_reg_1142_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4;
                ap_return_1_int_reg <= ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4;
                ap_return_2_int_reg <= ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4;
                ap_return_3_int_reg <= ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4;
                ap_return_4_int_reg <= ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4;
                ap_return_5_int_reg <= ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4;
                ap_return_6_int_reg <= ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4;
            end if;
        end if;
    end process;
    add_ln700_1_fu_596_p2 <= std_logic_vector(unsigned(tmp_1_fu_577_p9) + unsigned(ap_const_lv3_1));
    add_ln700_2_fu_768_p2 <= std_logic_vector(unsigned(tmp_2_fu_749_p9) + unsigned(ap_const_lv3_1));
    add_ln700_3_fu_940_p2 <= std_logic_vector(unsigned(tmp_3_fu_921_p9) + unsigned(ap_const_lv3_1));
    add_ln700_fu_417_p2 <= std_logic_vector(unsigned(tmp_fu_397_p9) + unsigned(ap_const_lv3_1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4_assign_proc : process(stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257, LRHLS_layersPopulation_0_V_6_fu_1078_p10, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_7_reg_327)
    begin
        if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_0)) then 
            ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257;
        elsif ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_1)) then 
            ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4 <= LRHLS_layersPopulation_0_V_6_fu_1078_p10;
        else 
            ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_7_reg_327;
        end if; 
    end process;


    ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4_assign_proc : process(stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267, LRHLS_layersPopulation_1_V_6_fu_1056_p10, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_7_reg_337)
    begin
        if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_0)) then 
            ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267;
        elsif ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_1)) then 
            ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4 <= LRHLS_layersPopulation_1_V_6_fu_1056_p10;
        else 
            ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_7_reg_337;
        end if; 
    end process;


    ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4_assign_proc : process(stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277, LRHLS_layersPopulation_2_V_6_fu_1034_p10, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_7_reg_347)
    begin
        if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_0)) then 
            ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277;
        elsif ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_1)) then 
            ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4 <= LRHLS_layersPopulation_2_V_6_fu_1034_p10;
        else 
            ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_7_reg_347;
        end if; 
    end process;


    ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4_assign_proc : process(stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287, LRHLS_layersPopulation_3_V_6_fu_1012_p10, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_7_reg_357)
    begin
        if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_0)) then 
            ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287;
        elsif ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_1)) then 
            ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4 <= LRHLS_layersPopulation_3_V_6_fu_1012_p10;
        else 
            ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_7_reg_357;
        end if; 
    end process;


    ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4_assign_proc : process(stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297, LRHLS_layersPopulation_4_V_6_fu_990_p10, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_7_reg_367)
    begin
        if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_0)) then 
            ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297;
        elsif ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_1)) then 
            ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4 <= LRHLS_layersPopulation_4_V_6_fu_990_p10;
        else 
            ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_7_reg_367;
        end if; 
    end process;


    ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4_assign_proc : process(stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307, LRHLS_layersPopulation_5_V_6_fu_968_p10, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_7_reg_377)
    begin
        if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_0)) then 
            ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307;
        elsif ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_1)) then 
            ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4 <= LRHLS_layersPopulation_5_V_6_fu_968_p10;
        else 
            ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_7_reg_377;
        end if; 
    end process;


    ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4_assign_proc : process(stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317, LRHLS_layersPopulation_6_V_6_fu_946_p10, ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_7_reg_387)
    begin
        if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_0)) then 
            ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317;
        elsif ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg = ap_const_lv1_1)) then 
            ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4 <= LRHLS_layersPopulation_6_V_6_fu_946_p10;
        else 
            ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4 <= ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_7_reg_387;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_1_reg_102 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_3_reg_180 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_5_reg_257 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_1_reg_114 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_3_reg_191 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_5_reg_267 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_1_reg_126 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_3_reg_202 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_5_reg_277 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_1_reg_138 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_3_reg_213 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_5_reg_287 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_1_reg_150 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_3_reg_224 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_5_reg_297 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_1_reg_160 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_3_reg_235 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_5_reg_307 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_1_reg_170 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_3_reg_246 <= "XXX";
    ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_5_reg_317 <= "XXX";
    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_7_reg_327 <= "XXX";
    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_7_reg_337 <= "XXX";
    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_7_reg_347 <= "XXX";
    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_7_reg_357 <= "XXX";
    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_7_reg_367 <= "XXX";
    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_7_reg_377 <= "XXX";
    ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_7_reg_387 <= "XXX";

    ap_return_0_assign_proc : process(ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4;
        end if; 
    end process;


    ap_return_5_assign_proc : process(ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4, ap_ce_reg, ap_return_5_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_5 <= ap_return_5_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_5 <= ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4;
        end if; 
    end process;


    ap_return_6_assign_proc : process(ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4, ap_ce_reg, ap_return_6_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_6 <= ap_return_6_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_6 <= ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4;
        end if; 
    end process;

    stubs_0_valid_V_read_2_read_fu_54_p2 <= stubs_0_valid_V_read_int_reg;
end behav;
