// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module findLayersPopulation (
        ap_clk,
        ap_rst,
        LRHLS_layersPopulation_4_V_read,
        LRHLS_layersPopulation_5_V_read,
        LRHLS_layersPopulation_6_V_read,
        stubs_0_layer_V_read,
        stubs_1_layer_V_read,
        stubs_2_layer_V_read,
        stubs_3_layer_V_read,
        stubs_0_valid_V_read,
        stubs_1_valid_V_read,
        stubs_2_valid_V_read,
        stubs_3_valid_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [2:0] LRHLS_layersPopulation_4_V_read;
input  [2:0] LRHLS_layersPopulation_5_V_read;
input  [2:0] LRHLS_layersPopulation_6_V_read;
input  [2:0] stubs_0_layer_V_read;
input  [2:0] stubs_1_layer_V_read;
input  [2:0] stubs_2_layer_V_read;
input  [2:0] stubs_3_layer_V_read;
input  [0:0] stubs_0_valid_V_read;
input  [0:0] stubs_1_valid_V_read;
input  [0:0] stubs_2_valid_V_read;
input  [0:0] stubs_3_valid_V_read;
output  [2:0] ap_return_0;
output  [2:0] ap_return_1;
output  [2:0] ap_return_2;
output  [2:0] ap_return_3;
output  [2:0] ap_return_4;
output  [2:0] ap_return_5;
output  [2:0] ap_return_6;
input   ap_ce;

reg[2:0] ap_return_0;
reg[2:0] ap_return_1;
reg[2:0] ap_return_2;
reg[2:0] ap_return_3;
reg[2:0] ap_return_4;
reg[2:0] ap_return_5;
reg[2:0] ap_return_6;

reg   [0:0] stubs_3_valid_V_read11_reg_1142;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] stubs_3_valid_V_read11_reg_1142_pp0_iter1_reg;
reg   [0:0] stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg;
reg   [0:0] stubs_2_valid_V_read_2_reg_1146;
reg   [0:0] stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg;
reg   [0:0] stubs_1_valid_V_read_2_reg_1150;
reg   [2:0] stubs_3_layer_V_read_2_reg_1157;
reg   [2:0] stubs_3_layer_V_read_2_reg_1157_pp0_iter1_reg;
reg   [2:0] stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg;
reg   [2:0] stubs_2_layer_V_read_2_reg_1169;
reg   [2:0] stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg;
reg   [2:0] stubs_1_layer_V_read_2_reg_1181;
wire   [2:0] LRHLS_layersPopulation_6_V_fu_423_p10;
wire   [0:0] stubs_0_valid_V_read_2_read_fu_54_p2;
wire   [2:0] LRHLS_layersPopulation_5_V_fu_445_p10;
wire   [2:0] LRHLS_layersPopulation_4_V_fu_467_p10;
wire   [2:0] LRHLS_layersPopulation_3_V_fu_489_p10;
wire   [2:0] LRHLS_layersPopulation_2_V_fu_511_p10;
wire   [2:0] LRHLS_layersPopulation_1_V_fu_533_p10;
wire   [2:0] LRHLS_layersPopulation_0_V_fu_555_p10;
wire   [2:0] LRHLS_layersPopulation_6_V_2_fu_602_p10;
wire   [2:0] LRHLS_layersPopulation_5_V_2_fu_623_p10;
wire   [2:0] LRHLS_layersPopulation_4_V_2_fu_644_p10;
wire   [2:0] LRHLS_layersPopulation_3_V_2_fu_665_p10;
wire   [2:0] LRHLS_layersPopulation_2_V_2_fu_686_p10;
wire   [2:0] LRHLS_layersPopulation_1_V_2_fu_707_p10;
wire   [2:0] LRHLS_layersPopulation_0_V_2_fu_728_p10;
wire   [2:0] LRHLS_layersPopulation_6_V_4_fu_774_p10;
wire   [2:0] LRHLS_layersPopulation_5_V_4_fu_795_p10;
wire   [2:0] LRHLS_layersPopulation_4_V_4_fu_816_p10;
wire   [2:0] LRHLS_layersPopulation_3_V_4_fu_837_p10;
wire   [2:0] LRHLS_layersPopulation_2_V_4_fu_858_p10;
wire   [2:0] LRHLS_layersPopulation_1_V_4_fu_879_p10;
wire   [2:0] LRHLS_layersPopulation_0_V_4_fu_900_p10;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_1_reg_102;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_1_reg_114;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_1_reg_126;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_1_reg_138;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_1_reg_150;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_1_reg_160;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_1_reg_170;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_3_reg_180;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_3_reg_180;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_3_reg_191;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_3_reg_191;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_3_reg_202;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_3_reg_202;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_3_reg_213;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_3_reg_213;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_3_reg_224;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_3_reg_224;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_3_reg_235;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_3_reg_235;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_3_reg_246;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_3_reg_246;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_5_reg_257;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_5_reg_257;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_5_reg_257;
reg   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_5_reg_267;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_5_reg_267;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_5_reg_267;
reg   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_5_reg_277;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_5_reg_277;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_5_reg_277;
reg   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_5_reg_287;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_5_reg_287;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_5_reg_287;
reg   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_5_reg_297;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_5_reg_297;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_5_reg_297;
reg   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_5_reg_307;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_5_reg_307;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_5_reg_307;
reg   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307;
wire   [2:0] ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_5_reg_317;
reg   [2:0] ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_5_reg_317;
reg   [2:0] ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_5_reg_317;
reg   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317;
reg   [2:0] ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4;
wire   [2:0] LRHLS_layersPopulation_0_V_6_fu_1078_p10;
wire   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_7_reg_327;
reg   [2:0] ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4;
wire   [2:0] LRHLS_layersPopulation_1_V_6_fu_1056_p10;
wire   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_7_reg_337;
reg   [2:0] ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4;
wire   [2:0] LRHLS_layersPopulation_2_V_6_fu_1034_p10;
wire   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_7_reg_347;
reg   [2:0] ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4;
wire   [2:0] LRHLS_layersPopulation_3_V_6_fu_1012_p10;
wire   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_7_reg_357;
reg   [2:0] ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4;
wire   [2:0] LRHLS_layersPopulation_4_V_6_fu_990_p10;
wire   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_7_reg_367;
reg   [2:0] ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4;
wire   [2:0] LRHLS_layersPopulation_5_V_6_fu_968_p10;
wire   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_7_reg_377;
reg   [2:0] ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4;
wire   [2:0] LRHLS_layersPopulation_6_V_6_fu_946_p10;
wire   [2:0] ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_7_reg_387;
wire    ap_block_pp0_stage0;
wire   [2:0] tmp_fu_397_p9;
wire   [2:0] add_ln700_fu_417_p2;
wire   [2:0] tmp_1_fu_577_p9;
wire   [2:0] add_ln700_1_fu_596_p2;
wire   [2:0] tmp_2_fu_749_p9;
wire   [2:0] add_ln700_2_fu_768_p2;
wire   [2:0] tmp_3_fu_921_p9;
wire   [2:0] add_ln700_3_fu_940_p2;
reg    ap_ce_reg;
reg   [2:0] LRHLS_layersPopulation_4_V_read_int_reg;
reg   [2:0] LRHLS_layersPopulation_5_V_read_int_reg;
reg   [2:0] LRHLS_layersPopulation_6_V_read_int_reg;
reg   [2:0] stubs_0_layer_V_read_int_reg;
reg   [2:0] stubs_1_layer_V_read_int_reg;
reg   [2:0] stubs_2_layer_V_read_int_reg;
reg   [2:0] stubs_3_layer_V_read_int_reg;
reg   [0:0] stubs_0_valid_V_read_int_reg;
reg   [0:0] stubs_1_valid_V_read_int_reg;
reg   [0:0] stubs_2_valid_V_read_int_reg;
reg   [0:0] stubs_3_valid_V_read_int_reg;
reg   [2:0] ap_return_0_int_reg;
reg   [2:0] ap_return_1_int_reg;
reg   [2:0] ap_return_2_int_reg;
reg   [2:0] ap_return_3_int_reg;
reg   [2:0] ap_return_4_int_reg;
reg   [2:0] ap_return_5_int_reg;
reg   [2:0] ap_return_6_int_reg;

LRHLS_top_mux_73_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_73_3_1_0_U21(
    .din0(3'd0),
    .din1(3'd0),
    .din2(3'd0),
    .din3(3'd0),
    .din4(LRHLS_layersPopulation_4_V_read_int_reg),
    .din5(LRHLS_layersPopulation_5_V_read_int_reg),
    .din6(LRHLS_layersPopulation_6_V_read_int_reg),
    .din7(stubs_0_layer_V_read_int_reg),
    .dout(tmp_fu_397_p9)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U22(
    .din0(LRHLS_layersPopulation_6_V_read_int_reg),
    .din1(LRHLS_layersPopulation_6_V_read_int_reg),
    .din2(LRHLS_layersPopulation_6_V_read_int_reg),
    .din3(LRHLS_layersPopulation_6_V_read_int_reg),
    .din4(LRHLS_layersPopulation_6_V_read_int_reg),
    .din5(LRHLS_layersPopulation_6_V_read_int_reg),
    .din6(add_ln700_fu_417_p2),
    .din7(add_ln700_fu_417_p2),
    .din8(stubs_0_layer_V_read_int_reg),
    .dout(LRHLS_layersPopulation_6_V_fu_423_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U23(
    .din0(LRHLS_layersPopulation_5_V_read_int_reg),
    .din1(LRHLS_layersPopulation_5_V_read_int_reg),
    .din2(LRHLS_layersPopulation_5_V_read_int_reg),
    .din3(LRHLS_layersPopulation_5_V_read_int_reg),
    .din4(LRHLS_layersPopulation_5_V_read_int_reg),
    .din5(add_ln700_fu_417_p2),
    .din6(LRHLS_layersPopulation_5_V_read_int_reg),
    .din7(LRHLS_layersPopulation_5_V_read_int_reg),
    .din8(stubs_0_layer_V_read_int_reg),
    .dout(LRHLS_layersPopulation_5_V_fu_445_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U24(
    .din0(LRHLS_layersPopulation_4_V_read_int_reg),
    .din1(LRHLS_layersPopulation_4_V_read_int_reg),
    .din2(LRHLS_layersPopulation_4_V_read_int_reg),
    .din3(LRHLS_layersPopulation_4_V_read_int_reg),
    .din4(add_ln700_fu_417_p2),
    .din5(LRHLS_layersPopulation_4_V_read_int_reg),
    .din6(LRHLS_layersPopulation_4_V_read_int_reg),
    .din7(LRHLS_layersPopulation_4_V_read_int_reg),
    .din8(stubs_0_layer_V_read_int_reg),
    .dout(LRHLS_layersPopulation_4_V_fu_467_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U25(
    .din0(3'd0),
    .din1(3'd0),
    .din2(3'd0),
    .din3(add_ln700_fu_417_p2),
    .din4(3'd0),
    .din5(3'd0),
    .din6(3'd0),
    .din7(3'd0),
    .din8(stubs_0_layer_V_read_int_reg),
    .dout(LRHLS_layersPopulation_3_V_fu_489_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U26(
    .din0(3'd0),
    .din1(3'd0),
    .din2(add_ln700_fu_417_p2),
    .din3(3'd0),
    .din4(3'd0),
    .din5(3'd0),
    .din6(3'd0),
    .din7(3'd0),
    .din8(stubs_0_layer_V_read_int_reg),
    .dout(LRHLS_layersPopulation_2_V_fu_511_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U27(
    .din0(3'd0),
    .din1(add_ln700_fu_417_p2),
    .din2(3'd0),
    .din3(3'd0),
    .din4(3'd0),
    .din5(3'd0),
    .din6(3'd0),
    .din7(3'd0),
    .din8(stubs_0_layer_V_read_int_reg),
    .dout(LRHLS_layersPopulation_1_V_fu_533_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U28(
    .din0(add_ln700_fu_417_p2),
    .din1(3'd0),
    .din2(3'd0),
    .din3(3'd0),
    .din4(3'd0),
    .din5(3'd0),
    .din6(3'd0),
    .din7(3'd0),
    .din8(stubs_0_layer_V_read_int_reg),
    .dout(LRHLS_layersPopulation_0_V_fu_555_p10)
);

LRHLS_top_mux_73_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_73_3_1_0_U29(
    .din0(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din1(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din2(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din3(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din4(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din5(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din6(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170),
    .din7(stubs_1_layer_V_read_2_reg_1181),
    .dout(tmp_1_fu_577_p9)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U30(
    .din0(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170),
    .din1(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170),
    .din2(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170),
    .din3(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170),
    .din4(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170),
    .din5(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170),
    .din6(add_ln700_1_fu_596_p2),
    .din7(add_ln700_1_fu_596_p2),
    .din8(stubs_1_layer_V_read_2_reg_1181),
    .dout(LRHLS_layersPopulation_6_V_2_fu_602_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U31(
    .din0(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din1(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din2(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din3(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din4(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din5(add_ln700_1_fu_596_p2),
    .din6(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din7(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160),
    .din8(stubs_1_layer_V_read_2_reg_1181),
    .dout(LRHLS_layersPopulation_5_V_2_fu_623_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U32(
    .din0(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din1(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din2(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din3(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din4(add_ln700_1_fu_596_p2),
    .din5(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din6(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din7(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150),
    .din8(stubs_1_layer_V_read_2_reg_1181),
    .dout(LRHLS_layersPopulation_4_V_2_fu_644_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U33(
    .din0(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din1(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din2(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din3(add_ln700_1_fu_596_p2),
    .din4(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din5(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din6(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din7(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138),
    .din8(stubs_1_layer_V_read_2_reg_1181),
    .dout(LRHLS_layersPopulation_3_V_2_fu_665_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U34(
    .din0(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din1(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din2(add_ln700_1_fu_596_p2),
    .din3(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din4(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din5(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din6(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din7(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126),
    .din8(stubs_1_layer_V_read_2_reg_1181),
    .dout(LRHLS_layersPopulation_2_V_2_fu_686_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U35(
    .din0(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din1(add_ln700_1_fu_596_p2),
    .din2(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din3(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din4(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din5(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din6(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din7(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114),
    .din8(stubs_1_layer_V_read_2_reg_1181),
    .dout(LRHLS_layersPopulation_1_V_2_fu_707_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U36(
    .din0(add_ln700_1_fu_596_p2),
    .din1(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din2(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din3(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din4(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din5(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din6(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din7(ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102),
    .din8(stubs_1_layer_V_read_2_reg_1181),
    .dout(LRHLS_layersPopulation_0_V_2_fu_728_p10)
);

LRHLS_top_mux_73_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_73_3_1_0_U37(
    .din0(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din1(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din2(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din3(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din4(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din5(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din6(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246),
    .din7(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(tmp_2_fu_749_p9)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U38(
    .din0(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246),
    .din1(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246),
    .din2(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246),
    .din3(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246),
    .din4(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246),
    .din5(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246),
    .din6(add_ln700_2_fu_768_p2),
    .din7(add_ln700_2_fu_768_p2),
    .din8(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(LRHLS_layersPopulation_6_V_4_fu_774_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U39(
    .din0(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din1(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din2(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din3(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din4(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din5(add_ln700_2_fu_768_p2),
    .din6(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din7(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235),
    .din8(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(LRHLS_layersPopulation_5_V_4_fu_795_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U40(
    .din0(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din1(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din2(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din3(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din4(add_ln700_2_fu_768_p2),
    .din5(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din6(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din7(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224),
    .din8(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(LRHLS_layersPopulation_4_V_4_fu_816_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U41(
    .din0(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din1(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din2(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din3(add_ln700_2_fu_768_p2),
    .din4(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din5(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din6(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din7(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213),
    .din8(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(LRHLS_layersPopulation_3_V_4_fu_837_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U42(
    .din0(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din1(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din2(add_ln700_2_fu_768_p2),
    .din3(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din4(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din5(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din6(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din7(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202),
    .din8(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(LRHLS_layersPopulation_2_V_4_fu_858_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U43(
    .din0(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din1(add_ln700_2_fu_768_p2),
    .din2(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din3(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din4(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din5(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din6(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din7(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191),
    .din8(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(LRHLS_layersPopulation_1_V_4_fu_879_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U44(
    .din0(add_ln700_2_fu_768_p2),
    .din1(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din2(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din3(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din4(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din5(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din6(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din7(ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180),
    .din8(stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg),
    .dout(LRHLS_layersPopulation_0_V_4_fu_900_p10)
);

LRHLS_top_mux_73_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_73_3_1_0_U45(
    .din0(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din1(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din2(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din3(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din4(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din5(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din6(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317),
    .din7(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(tmp_3_fu_921_p9)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U46(
    .din0(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317),
    .din1(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317),
    .din2(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317),
    .din3(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317),
    .din4(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317),
    .din5(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317),
    .din6(add_ln700_3_fu_940_p2),
    .din7(add_ln700_3_fu_940_p2),
    .din8(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(LRHLS_layersPopulation_6_V_6_fu_946_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U47(
    .din0(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din1(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din2(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din3(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din4(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din5(add_ln700_3_fu_940_p2),
    .din6(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din7(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307),
    .din8(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(LRHLS_layersPopulation_5_V_6_fu_968_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U48(
    .din0(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din1(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din2(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din3(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din4(add_ln700_3_fu_940_p2),
    .din5(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din6(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din7(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297),
    .din8(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(LRHLS_layersPopulation_4_V_6_fu_990_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U49(
    .din0(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din1(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din2(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din3(add_ln700_3_fu_940_p2),
    .din4(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din5(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din6(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din7(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287),
    .din8(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(LRHLS_layersPopulation_3_V_6_fu_1012_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U50(
    .din0(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din1(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din2(add_ln700_3_fu_940_p2),
    .din3(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din4(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din5(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din6(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din7(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277),
    .din8(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(LRHLS_layersPopulation_2_V_6_fu_1034_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U51(
    .din0(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din1(add_ln700_3_fu_940_p2),
    .din2(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din3(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din4(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din5(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din6(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din7(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267),
    .din8(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(LRHLS_layersPopulation_1_V_6_fu_1056_p10)
);

LRHLS_top_mux_83_3_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
LRHLS_top_mux_83_3_1_0_U52(
    .din0(add_ln700_3_fu_940_p2),
    .din1(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din2(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din3(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din4(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din5(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din6(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din7(ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257),
    .din8(stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg),
    .dout(LRHLS_layersPopulation_0_V_6_fu_1078_p10)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102 <= 3'd0;
        end else if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102 <= LRHLS_layersPopulation_0_V_fu_555_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_1_reg_102;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114 <= 3'd0;
        end else if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114 <= LRHLS_layersPopulation_1_V_fu_533_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_1_reg_114;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126 <= 3'd0;
        end else if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126 <= LRHLS_layersPopulation_2_V_fu_511_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_1_reg_126;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138 <= 3'd0;
        end else if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138 <= LRHLS_layersPopulation_3_V_fu_489_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_1_reg_138;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150 <= LRHLS_layersPopulation_4_V_read_int_reg;
        end else if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150 <= LRHLS_layersPopulation_4_V_fu_467_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_1_reg_150;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160 <= LRHLS_layersPopulation_5_V_read_int_reg;
        end else if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160 <= LRHLS_layersPopulation_5_V_fu_445_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_1_reg_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170 <= LRHLS_layersPopulation_6_V_read_int_reg;
        end else if ((stubs_0_valid_V_read_2_read_fu_54_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170 <= LRHLS_layersPopulation_6_V_fu_423_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_1_reg_170;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_1_valid_V_read_2_reg_1150 == 1'd0)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_1_reg_102;
        end else if ((stubs_1_valid_V_read_2_reg_1150 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180 <= LRHLS_layersPopulation_0_V_2_fu_728_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_3_reg_180;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_1_valid_V_read_2_reg_1150 == 1'd0)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_1_reg_114;
        end else if ((stubs_1_valid_V_read_2_reg_1150 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191 <= LRHLS_layersPopulation_1_V_2_fu_707_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_3_reg_191;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_1_valid_V_read_2_reg_1150 == 1'd0)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_1_reg_126;
        end else if ((stubs_1_valid_V_read_2_reg_1150 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202 <= LRHLS_layersPopulation_2_V_2_fu_686_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_3_reg_202;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_1_valid_V_read_2_reg_1150 == 1'd0)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_1_reg_138;
        end else if ((stubs_1_valid_V_read_2_reg_1150 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213 <= LRHLS_layersPopulation_3_V_2_fu_665_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_3_reg_213;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_1_valid_V_read_2_reg_1150 == 1'd0)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_1_reg_150;
        end else if ((stubs_1_valid_V_read_2_reg_1150 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224 <= LRHLS_layersPopulation_4_V_2_fu_644_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_3_reg_224;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_1_valid_V_read_2_reg_1150 == 1'd0)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_1_reg_160;
        end else if ((stubs_1_valid_V_read_2_reg_1150 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235 <= LRHLS_layersPopulation_5_V_2_fu_623_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_3_reg_235;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_1_valid_V_read_2_reg_1150 == 1'd0)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_1_reg_170;
        end else if ((stubs_1_valid_V_read_2_reg_1150 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246 <= LRHLS_layersPopulation_6_V_2_fu_602_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_3_reg_246;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_3_reg_180;
        end else if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257 <= LRHLS_layersPopulation_0_V_4_fu_900_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_5_reg_257;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_3_reg_191;
        end else if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267 <= LRHLS_layersPopulation_1_V_4_fu_879_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_5_reg_267;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_3_reg_202;
        end else if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277 <= LRHLS_layersPopulation_2_V_4_fu_858_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_5_reg_277;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_3_reg_213;
        end else if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287 <= LRHLS_layersPopulation_3_V_4_fu_837_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_5_reg_287;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_3_reg_224;
        end else if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297 <= LRHLS_layersPopulation_4_V_4_fu_816_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_5_reg_297;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_3_reg_235;
        end else if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307 <= LRHLS_layersPopulation_5_V_4_fu_795_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_5_reg_307;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_3_reg_246;
        end else if ((stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317 <= LRHLS_layersPopulation_6_V_4_fu_774_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_5_reg_317;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        LRHLS_layersPopulation_4_V_read_int_reg <= LRHLS_layersPopulation_4_V_read;
        LRHLS_layersPopulation_5_V_read_int_reg <= LRHLS_layersPopulation_5_V_read;
        LRHLS_layersPopulation_6_V_read_int_reg <= LRHLS_layersPopulation_6_V_read;
        stubs_0_layer_V_read_int_reg <= stubs_0_layer_V_read;
        stubs_0_valid_V_read_int_reg <= stubs_0_valid_V_read;
        stubs_1_layer_V_read_int_reg <= stubs_1_layer_V_read;
        stubs_1_valid_V_read_int_reg <= stubs_1_valid_V_read;
        stubs_2_layer_V_read_int_reg <= stubs_2_layer_V_read;
        stubs_2_valid_V_read_int_reg <= stubs_2_valid_V_read;
        stubs_3_layer_V_read_int_reg <= stubs_3_layer_V_read;
        stubs_3_valid_V_read_int_reg <= stubs_3_valid_V_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_3_reg_180 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_3_reg_180;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_5_reg_257;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_3_reg_191 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_3_reg_191;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_5_reg_267;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_3_reg_202 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_3_reg_202;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_5_reg_277;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_3_reg_213 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_3_reg_213;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_5_reg_287;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_3_reg_224 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_3_reg_224;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_5_reg_297;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_3_reg_235 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_3_reg_235;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_5_reg_307;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_3_reg_246 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_3_reg_246;
        ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_5_reg_317;
        ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_0_V_5_reg_257 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_0_V_5_reg_257;
        ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_1_V_5_reg_267 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_1_V_5_reg_267;
        ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_2_V_5_reg_277 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_2_V_5_reg_277;
        ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_3_V_5_reg_287 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_3_V_5_reg_287;
        ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_4_V_5_reg_297 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_4_V_5_reg_297;
        ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_5_V_5_reg_307 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_5_V_5_reg_307;
        ap_phi_reg_pp0_iter2_LRHLS_layersPopulation_6_V_5_reg_317 <= ap_phi_reg_pp0_iter1_LRHLS_layersPopulation_6_V_5_reg_317;
        stubs_1_layer_V_read_2_reg_1181 <= stubs_1_layer_V_read_int_reg;
        stubs_1_valid_V_read_2_reg_1150 <= stubs_1_valid_V_read_int_reg;
        stubs_2_layer_V_read_2_reg_1169 <= stubs_2_layer_V_read_int_reg;
        stubs_2_layer_V_read_2_reg_1169_pp0_iter1_reg <= stubs_2_layer_V_read_2_reg_1169;
        stubs_2_valid_V_read_2_reg_1146 <= stubs_2_valid_V_read_int_reg;
        stubs_2_valid_V_read_2_reg_1146_pp0_iter1_reg <= stubs_2_valid_V_read_2_reg_1146;
        stubs_3_layer_V_read_2_reg_1157 <= stubs_3_layer_V_read_int_reg;
        stubs_3_layer_V_read_2_reg_1157_pp0_iter1_reg <= stubs_3_layer_V_read_2_reg_1157;
        stubs_3_layer_V_read_2_reg_1157_pp0_iter2_reg <= stubs_3_layer_V_read_2_reg_1157_pp0_iter1_reg;
        stubs_3_valid_V_read11_reg_1142 <= stubs_3_valid_V_read_int_reg;
        stubs_3_valid_V_read11_reg_1142_pp0_iter1_reg <= stubs_3_valid_V_read11_reg_1142;
        stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg <= stubs_3_valid_V_read11_reg_1142_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4;
        ap_return_1_int_reg <= ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4;
        ap_return_2_int_reg <= ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4;
        ap_return_3_int_reg <= ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4;
        ap_return_4_int_reg <= ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4;
        ap_return_5_int_reg <= ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4;
        ap_return_6_int_reg <= ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4;
    end
end

always @ (*) begin
    if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd0)) begin
        ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_5_reg_257;
    end else if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd1)) begin
        ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4 = LRHLS_layersPopulation_0_V_6_fu_1078_p10;
    end else begin
        ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_7_reg_327;
    end
end

always @ (*) begin
    if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd0)) begin
        ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_5_reg_267;
    end else if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd1)) begin
        ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4 = LRHLS_layersPopulation_1_V_6_fu_1056_p10;
    end else begin
        ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_7_reg_337;
    end
end

always @ (*) begin
    if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd0)) begin
        ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_5_reg_277;
    end else if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd1)) begin
        ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4 = LRHLS_layersPopulation_2_V_6_fu_1034_p10;
    end else begin
        ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_7_reg_347;
    end
end

always @ (*) begin
    if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd0)) begin
        ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_5_reg_287;
    end else if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd1)) begin
        ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4 = LRHLS_layersPopulation_3_V_6_fu_1012_p10;
    end else begin
        ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_7_reg_357;
    end
end

always @ (*) begin
    if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd0)) begin
        ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_5_reg_297;
    end else if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd1)) begin
        ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4 = LRHLS_layersPopulation_4_V_6_fu_990_p10;
    end else begin
        ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_7_reg_367;
    end
end

always @ (*) begin
    if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd0)) begin
        ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_5_reg_307;
    end else if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd1)) begin
        ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4 = LRHLS_layersPopulation_5_V_6_fu_968_p10;
    end else begin
        ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_7_reg_377;
    end
end

always @ (*) begin
    if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd0)) begin
        ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_5_reg_317;
    end else if ((stubs_3_valid_V_read11_reg_1142_pp0_iter2_reg == 1'd1)) begin
        ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4 = LRHLS_layersPopulation_6_V_6_fu_946_p10;
    end else begin
        ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4 = ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_7_reg_387;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = ap_phi_mux_LRHLS_layersPopulation_0_V_7_phi_fu_330_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = ap_phi_mux_LRHLS_layersPopulation_1_V_7_phi_fu_340_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = ap_phi_mux_LRHLS_layersPopulation_2_V_7_phi_fu_350_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = ap_phi_mux_LRHLS_layersPopulation_3_V_7_phi_fu_360_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = ap_phi_mux_LRHLS_layersPopulation_4_V_7_phi_fu_370_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = ap_phi_mux_LRHLS_layersPopulation_5_V_7_phi_fu_380_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = ap_phi_mux_LRHLS_layersPopulation_6_V_7_phi_fu_390_p4;
    end
end

assign add_ln700_1_fu_596_p2 = (tmp_1_fu_577_p9 + 3'd1);

assign add_ln700_2_fu_768_p2 = (tmp_2_fu_749_p9 + 3'd1);

assign add_ln700_3_fu_940_p2 = (tmp_3_fu_921_p9 + 3'd1);

assign add_ln700_fu_417_p2 = (tmp_fu_397_p9 + 3'd1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_1_reg_102 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_3_reg_180 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_0_V_5_reg_257 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_1_reg_114 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_3_reg_191 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_1_V_5_reg_267 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_1_reg_126 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_3_reg_202 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_2_V_5_reg_277 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_1_reg_138 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_3_reg_213 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_3_V_5_reg_287 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_1_reg_150 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_3_reg_224 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_4_V_5_reg_297 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_1_reg_160 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_3_reg_235 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_5_V_5_reg_307 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_1_reg_170 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_3_reg_246 = 'bx;

assign ap_phi_reg_pp0_iter0_LRHLS_layersPopulation_6_V_5_reg_317 = 'bx;

assign ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_0_V_7_reg_327 = 'bx;

assign ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_1_V_7_reg_337 = 'bx;

assign ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_2_V_7_reg_347 = 'bx;

assign ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_3_V_7_reg_357 = 'bx;

assign ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_4_V_7_reg_367 = 'bx;

assign ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_5_V_7_reg_377 = 'bx;

assign ap_phi_reg_pp0_iter3_LRHLS_layersPopulation_6_V_7_reg_387 = 'bx;

assign stubs_0_valid_V_read_2_read_fu_54_p2 = stubs_0_valid_V_read_int_reg;

endmodule //findLayersPopulation
